package pawkar.backend.enums;

public enum ERole {
    ROLE_USER,
    ROLE_ADMIN,
    PORTERO,
    DEFENSA_CENTRAL,
    DEFENSA_LATERAL_DERECHO,
    DEFENSA_LATERAL_IZQUIERDO,
    CARRILERO_DERECHO,
    CARRILERO_IZQUIERDO,
    LIBERO,
    MEDIOCENTRO_DEFENSIVO,
    MEDIOCENTRO_MIXTO,
    MEDIOCENTRO_OFENSIVO,
    INTERIOR_DERECHO,
    INTERIOR_IZQUIERDO,
    EXTREMO_DERECHO,
    EXTREMO_IZQUIERDO,
    SEGUNDO_DELANTERO,
    DELANTERO_CENTRO,
    FALSO_NUEVE,
    ORGANIZADOR,
    TODO_CAMPO,
    EXTREMO_INVERSO,
    DELANTERO_REFERENCIA,
    CAZADOR,
    PORTERO_LIBRE;
}